project:
  type: website
  render:
    - "*.qmd"
    - "!archived"

website:
  title: "Gordon Shotwell"
  twitter-card: true
  google-analytics: "UA-98228149-1"
  site-url: "https://shotwell.ca/"
  navbar:
    right:
      - about.qmd
      - text: Presentations
        menu: 
          - text: "Technical Debt is a Social Problem"
            href: presentations/tech-debt.qmd
          - text: "Building secure systems"
            href: presentations/secure-systems.qmd
      - icon: github
        href: https://github.com/GShotwell
      - icon: twitter
        href: https://bsky.app/profile/shotwell.ca
      - icon: flower2
        href: https://bsky.app/profile/shotwell.ca
  search: 
    location: navbar
    type: overlay
format:
  html:
    theme: sandstone
    css: styles.css



