baseurl = "/"
publishDir= "docs"
relativeurls = true
languageCode = "en-us"
title = "Gordon Shotwell"
theme = "hyde-y"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


# Copyright
copyright = "(c) 2017 Gordon Shotwell."

# "yaml", "toml", "json"
metaDataFormat = "yaml"

# pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "shotwell-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Gordon Shotwell"
    email = "g.e.shotwell@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    highlight = "solarized_light"
    brand = "Gordon Shotwell"
    sidebar = "left"
    github = "GShotwell"
    linkedin = "gshotwell"
    twitter = "@gshotwell"
    googleAnalytics = "UA-98228149-1"