baseurl = "/"
publishDir= "docs"
relativeurls = true
languageCode = "en-us"
title = "Gordon Shotwell"
theme = "hyde-y"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[[menu.main]]
    name = "About"
    url = "/about/"

    
[params]
    # You can use markdown here.
    highlight = "solarized_light"
    brand = "Gordon Shotwell"
    topline = "Law and Data Science"
    sidebar = "left"
    github = "GShotwell"
    linkedin = "gshotwell"
    twitter = "@gshotwell"



  
