baseurl = "/"
publishDir= "docs"
relativeurls = true
languageCode = "en-us"
title = "Gordon Shotwell"
theme = "hyde-y"
disqusShortname = "shotwell-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
rss = true
copyright = "(c) 2017 Gordon Shotwell."

[about]
    name = "About"
    url = "/about/"

    
[params]
    # You can use markdown here.
    highlight = "solarized_light"
    brand = "Gordon Shotwell"
    topline = "Law and Data Science"
    sidebar = "left"
    github = "GShotwell"
    linkedin = "gshotwell"
    twitter = "@gshotwell"
    googleAnalytics = "UA-98228149-1"



  
