# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://shotwell.ca/blog"
publishDir= "docs"
relativeurls = true

# Site title
title = "Gordon Shotwell"

# Copyright
copyright = "(c) 2017 yourname."

# Language
languageCode = "en-EN"

# "yaml", "toml", "json"
metaDataFormat = "yaml"

# theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "shotwell-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Gordon Shotwell"
    email = "g.e.shotwell@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    highlight = "solarized_light"
    brand = "Gordon Shotwell"
    sidebar = "left"
    github = "GShotwell"
    linkedin = "gshotwell"
    twitter = "@gshotwell"
    googleAnalytics = "UA-98228149-1"