---
title: "Why your company should act remote, even if it's not"
date: "2017-02-02T21:48:51-07:00"
---

When I first started working at Upworthy, I was worried that working with a team which was scattered across the continent would lead to a lonely, disconnected work environment. What I discovered was that the remote team was the most productive, connected group of people that I'd ever worked with. I think there are some lessons to be taken from effective remote teams which can be applied to all businesses whether they are remote or not. 

Most business choose to hire remote employees because they want to take advantage of gains from trade. Because the average developer salary in Nova Scotia is lower than that in California, if you hire remote workers then you get better people for less money. The barrier to making this trade is that remote employees often require changes to your company's workflow. I think that these changes are actually positive things which every company should do.

## Four ways remote workers create better workflows

1) Results oriented
2) Intentional communication
3) Project ownership
4) Unintentional documentation


