---
date: "2017-04-26"
output: html_document
title: A General Theory of Alternative Medicine
author: Gordon Shotwell
---

I have a strange relationship to alternative medicine. On the one hand, I've
worked in clinical settings and as a medical malpractice lawyer and so have seen
first hand the damage that bad clinical evidence can do to patients. On the
other I just love health fads. I go to a traditional chinese doctor, eat all
kinds of super foods, and do things like fast or swim in extremely cold water
for my health. For a long time I thought these two factors were kind of opposed
to one another, but lately I've been thinking about them as a coherent approach
to health promotion.

 

Instead of talking about alternative and conventional medicine, I think it’s
more useful to make a distinction between anecdotal and clinical evidence.
Anecdotal evidence is the kind of evidence we use for most of our decisions, we
obverse various things about the world in our own experience, remember some of
those things, and then make inferences about them. For instance if we get sick
after going to a sushi restaurant we infer that there must be something wrong
with their health practices. Most alternative medicine relies heavily on
anecdotal evidence. You might have a practitioner or group of practitioners who
all start recommending a particular therapy to a patient, and then they observe
in an ad-hoc way whether that therapy worked or didn’t work.

 

### The problem with alternative medicine

 

The main problem with alternative medicine, or really any kind of anecdotal
evidence is confirmation bias. Confirmation bias occurs whenever you tend to
collect or record evidence in a way which biases your sample to the success
cases. For instance if you evaluate the success of your product only by
interviewing the

 

 

The problem with clinical trials

Ensemble approach

Rules for gambling with your health

 

### Understanding Clinical Trials

Clinical trials are the 'gold standard' of medical practice. In an ideal world
every decision we make would be informed by a well designed placebo controlled
study, but that sadly is not now and never will be the case. There are a few
large biases in clinical trial desigg:

1.  Money
