---
title: "Why relying on open source contribution is (probably) discriminatory"
author: "Gordon Shotwell"
date: '2018-02-01'
output: html_document
---

I'm a lawyer by training, but started working in programming and data science a few years ago. One of the first pieces of advice that I received was to build up my online presence through Twitter and by contributing to open source projects. I did both of these things to one degree or another and it did really help both learn more about the field, build a network, and eventually find work. In fact whenever I feel imposter syndrome at work these days the content is mostly "What if the only reason they hired me was because of all of my excellent Twitter quips?" 

After thinking about this for a few years I've started to think about this as a form of discrimination, and I think tech companies should entirely stop relying on open source contributions for hiring practices. I'd like to make the argument for this in the context of Canadian human rights law mostly beause it provides a precise framework for talking about the issue which I think helps to focus hiring discussions. 

## 30 second background to Canadian human rights law

Canadian rights law developed very late relative to the United States (the Charter of Rights and Freedoms was adopted in 1982) and as a result it includes a few parts which were designed to correct for deficiencies in other human rights regimes. One of the key parts of this framework is that it separate the question of whether something is a rights violation from whether it should be allowed. For instance, it's common in Canadian freedom of expression cases to end with a court finding that something is a freedom of expression violation, but that the government is justified in violating that right. American rights tend to be more absolute, something either is or is not a rights violation, and if it is one then the government is not allowed to do that thing. 

In Canada, hiring discrimination is governed by a set of human rights acts which more or less follow the same : 

1) Is the practice discriminatory?
2) Is that discrimination based on one of the grounds listed in the act?
3) Is there a very good reason for discrimination?

For example you might have an insurance scheme which charged people differently based on how old they are. This would be discriminatory because it provides a benefit ot young people that it's provided to older people (#1), age is a listed groung (#2) 