---
title: "Mapping a Redux Store with R"
date: "2017-03-27T21:48:51-07:00"
---

For the past few weeks I've been working on refactoring my meditation app to make use of Redux, and I just ran into a problem which makes excellent use of some of R's great programming constructs, and so I thought I'd write about it. 
## Backgound
The mobile app is written in React Native which is a wonderful way to get started with mobile app development. React Native is based on React which is a JavaScript framework for functional specification of user interfaces. The idea behind React is that you break your user interface into a bunch of different self contained pieces, and then write a function which returns that piece of the interface. Rather than writing code which displays three buttons, you write a function which returns a single button, and then call that function three times. The function is called a component. 

The great virtue of React is that it makes it very easy to compartmentalize your application. By default, each component is self-contained and all of the styling, state, and helper functions that the componet has access to are contained in the component file. This means that you can change parts of the UI and have confidence that those changes won't cause problems for other parts of the app. 

The problem with this approach is that it becomes difficult to keep all of the different compoenents in synch. For intance the Shambhala App has many components which all change appearance if the user is subscribed. So in order to make sure that all of those componets are consistent I have to pass an `is_subscribed` value down through all of the components. This makes the code harder to understand, and more fragile. 

## Enter Redux
Redux is a library which provides a global state for React. It allows each component to connect to a global state object to get and edit values. In a Redux world rather than passing the `is_subscribed` variable down through al the components, I can just connect the components that need the value to the `is_subscribed` value which is stored in state. This is great because it's easier to make sure that the application is consistent, but it makes it more vulnerable to unexpected side effects. For instance if I change the possible values of `is_subscribed` I need to make sure that I check all of the components which use it to make sure that nothing got borked. To do this you need to know all of the dependencies for each bit of state. 

I'm sure there are lots of great ways to solve this problem, but I'm going to solve it through documentation by using R to draw a map of my redux application.

## The parts of Redux

Redux is composed of a Store, Actions, and Reducers. These are terrible, unintuitive names, but I've come up with an analogy which helps me keep it straight. The redux store is like a custom clothing store. Any component go to the store and buy pants, shirts, or dresses, but if they want to change what's in the store they need to send in a special order to the factory. The order has some information identifying what they want made, and also includes some other stuff. Maybe a component wishes the store stocked tweed pants, and so sends in an order which says "MAKE PANTS" and includes a bunch of tweed fabric. This order might seem a little terse, but it turns out that the factory has a detailed set of instructions to execute whenever they receive an order which says "MAKE PANTS". They first cut up whatever fabric is included in an order, then sew it into pants, and finally send it to the shelf where it can be retrieved by the component. 

In Redux terms, the store is, well, the clothing store, the Action is the order, and the Reducer is the factory. Actions don't do anything in and of themselves they just trigger the reducer to do something and 















