---
title: What are we waiting for?
author: ~
date: '2020-03-18'
slug: what-are-we-waiting-for
categories: []
tags: []
lastmod: '2020-03-18T08:36:56-03:00'
layout: post
type: post
highlight: no
---

**Insert Lead paragraph here.**

A augue nunc lacus auctor efficitur tempor placerat, dictum volutpat mi vitae viverra porta non sem, himenaeos senectus vivamus potenti cubilia sollicitudin. Curae cursus inceptos tincidunt magna mi nibh ad enim etiam, molestie eu quis primis hendrerit taciti phasellus. Feugiat ultricies dictumst iaculis potenti odio laoreet urna at, ultrices curae leo accumsan proin sem lobortis. 

About five years ago I was diagnosed with multiple sclerosis. 
In my memory, that time in my life is broken up into little fragments. 
I remember my feet feeling numb as though my shoes had been laced up to tightly. 
I remember that numbness moving up my body day by day until I couldn't really feel much from the chest down. 
I remember walking to the MRI clinic before dawn through tall Nova Scotian snow banks. 
I remember how my doctor looked when she told me that there were probably lesions on my spine. 
I remember getting a spinal tap and later lying on the bathroom floor at work waiting for the resulting headache to disapate.

Most of all I remeber the overwhelming sense of pointlessness and nihilism that results from a diagnosis like that. 
MS is a very depressing disease, because it's neurological it can effect every part of your personhood, and because it's degenerative and uncured there's a sense that your life after diagnosis is just a slow, painful journey towards disability and death.
People say *still* and *yet* a lot when talking about MS.
"You can *still* go to work"; "you're not in a wheelchair *yet*"; as though you should live your life in anticipation of some dark, difficult to imagine future where these things will no longer be true.

This nihilism is dangerous because it prevents you from doing all the litle things that meaningfully improve your life. 
After all, if I'm inevitably going to get sicker, what's the point of starting a course of treatment? What's the point of doing anything really?

The reason I wanted to write about this is that I've noticed a similar kind of nihilism when thinking about the coronavirus pandemic. 
I look at the infection rate, the number of ICU beds, and the time it takes to develop a vaccine and I don't see much reason to hope.
It seems like if we're going to end up like Italy anyway, what's the point of flattening the curve? What's the point of hope?

# You don't know anything

I haven't had any MS relapses for five years, and I've been symptom free for three of those years. 
In that time I've changed careers, bought a house with stairs, and had a daughter, and I credit all of that to the fact that I ignored the part of my mind that reasons its way into the worst case scenario.
The reality of medicine is that we rarely know how things are going to go because knowledge and treatment can move extremely quickly. 
HIV was a death sentence until it wasn't, MS was untreatable until it was treated, and coronavirus is a existential threat to our society until it's not.
The thing is that we have no real ability to forecast when or how this knowledge will be discovered, so the best thing we can do is to try to maintain our health until we get there. 
The way I thought about this five years ago was that at some point, there's going to be a cure, or cure-like treatment for MS, and the best thing I can do is to try to delay disease progression until that happened. 

# COVID-19






