---
title: What's the blockchain good for anyway?
author: Gordon Shotwell
date: '2021-12-02'
slug: what-are-blockchains-good-for-anyway.en-us
categories: []
tags: []
keywords:
  - tech
---

People have invested about \$3 trillion in blockchain technologies globally, but it's still pretty hard to understand the value that is being produced by this technology. Can we really do anything now that we couldn't do before? Is the whole industry just a giant financial bubble or is there real value?

Most new technologies go through this phase. For example in the late 1990s the internet and e-commerce seemed like a transformative technology, but all of the examples of that technology were kind of silly. Looking back on this era, it's clear that a revolution was starting, but the way that society changed was pretty different from how people thought it was going to change, and the successfully companies to come our of that era were not the ones most people picked.

The new thing that blockchains offer the world is that they have three qualities:

1.  They can make complicated decisions

2.  They do not need a centralized authority

3.  The decisions can be made by computers

Various pieces of technology can do one or two of these things. For example, things like Google and Facebook can make complicated decisions in an automated way, but they're centralized services. Similarly, Wikipedia, or most financial markets are examples of distributed decision making, but they rely on a lot of human judgment and conversation and are difficult to automate. We also have distributed, automated things like internet protocols, but those protocols can't really complicated decisions.

Blockchains really are the first technology that can do all three of these things at the same time, but that comes at a cost. In order to enable distributed automated decision-making, blockchains will use much more code, energy, and compute infrastructure than traditional computer programs. Thinking about blockchains this way makes it easier to see why they might have value. If blockchains are valuable it's either because they are able to distribute centralized decisions, or because they can automate distributed decisions.

### **Distribute the automated things**

Most of the blockchain use cases that people know about fall into the category of taking a centralized automated process and distributing it. For example replacing the US Dollar with Bitcoin involves taking an incredibly efficient centralized process and distributing it. A blockchain will only succeed in this area if the value of decentralization exceeds the additional friction which would be introduced by inefficient computation.

I'm not optimistic about these use cases because most people trust these institutions. The US federal reserve is one of the most robust institutions in human history and unless something significant changes, I don't see the majority of people accepting inefficient transactions in order to avoid the centralized body. Similarly while it's possible that a blockchain-based social media protocol may be able to avoid some of the problems with Facebook or Twitter, I don't think that people care very much about the problems with those companies so I don't think they will accept a bad user experience in order to avoid using a centralized service.

### **Automated the distributed things**

Before blockchains we needed to centralize a process before we could automate it. Before you could start using a machine algorithm or a database to make decisions about something you needed to get everyone to use a centralized system to make those decisions. As a result if something is difficult to centralize it is difficult to automate. For example there's no centralized ledger of international currency transactions because people don't trust such a ledger. As a result, sending money around the world involves a lot of individual transactions, intermediaries, and counter party risk. As a result it takes a long time, and costs a lot of money, and isn't available to everyone. If there were some benevolent deity would faithfully maintain a database of all these transactions we could automate this process, but there's no such deity so people need to rely on long chains of currency trades to get the job done.

Blockchains have the potential to revolutionize these processes because it allows people to automate them without the need for a centralized authority. The value proposition is the same as every disruption in the information age: take something that is done by humans and figure out how to get computers to do it. The important thing about these use cases is that the blockchain solution is not competing with a centralized automated solution because centralization isn't feasible. This means that the inherent inefficiencies of blockchain-based solutions don't matter that much because they're still way more efficient than what they're replacing. For example think of the energy that's required to support all of currency traders in the world, the food that they eat, the buildings that they work in, the cars that they drive. Even if the blockchain that replaces them is less efficient than a centralized database, it's still much more efficient than what we're using today.

When you start thinking about these types of use-cases for blockchains you see them everywhere. For example consider some of the problems with scientific publishing.

### Example: scientific publishing

Currently scientific work is verified in a somewhat adhoc, distributed manner. People maybe put their work up on a pre-print server, then publish it in a journal, and in some rare cases make their data and code available to the public.

After a work is published, there's no real way of continuing to verify that it is correct or complete. If a future researcher wants to go back and check whether a paper was retracted, or invalidated, they need to do a literature review of later citations. Similarly if the shared data or code is taken down from where ever it was shared, there' no real mechanism for recovering it.

These are the kinds of problems which are easy to solve with a centralized database. We could imagine some central repository of all published scientific work, and post-publication issues could be noted in that repository. Whenever a researcher wanted to check if the paper had been retracted or called into question they could just look it up on this central repository.

This seems like a good solution until you realize that we've had databases for 50 years and nobody has gone ahead and created such a repository. This is because there are obstacles to centralization which makes it difficult to do this easy automation work. Some these include:

-   Financial incentives do not support centralized publishing

-   Having all scientific knowledge in one database is fragile

-   Journals have strong incentives to support the status quo

With blockchains you could imagine an automation strategy that doesn't require centralization. Information about papers could be tracked on a blockchain, and when a paper was retracted, that information would be noted in the paper's record. You could even imagine paying researchers in SciCoin to do peer and post-publication review on papers, or to maintain copies of data and code.

The important thing about this it's possible to get the benefits of automation without needing to first centralize the process. Note that it doesn't really matter whether this distributed automation is less efficient than centralized automation, because centralized automation is not currently possible.

### Conclusion

I think this framework is helpful for both blockchain proponents and skeptics. Before declaring that blockchain is the future of something or a giant wast of time, ask whether it's automating something distributed, or distributing something automated.
